version: 2

models:
  - name: stg_races_result
    description: The race results table.
    columns:
      - name: driver_id
        description: Foreign key to stg_drivers.driverId
        tests:
          - not_null
          - relationships:
              to: ref('stg_drivers')
              field: driver_id
      - name: constructor_id
        description: Foreign key to stg_constructors.constructorId
        tests:
          - not_null
          - relationships:
              to: ref('stg_constructors')
              field: constructor_id
      - name: circuit_id
        description: Foreign key to stg_circuits.circuitId
        tests:
          - not_null
          - relationships:
              to: ref('stg_circuits')
              field: circuit_id
      - name: status
        description: Status of each driver's race/car
        tests:
          - accepted_values:
              values: ['+1 Lap', '+2 Laps', '+3 Laps', '+4 Laps', '+5 Laps', '+6 Laps', '+8 Laps', 'Accident', 'Alternator', 
              'Battery', 'Brake duct', 'Brakes', 'Clutch', 'Collision', 'Collision damage', 'Cooling system', 'Damage', 'Debris', 
              'Differential', 'Disqualified', 'Driveshaft', 'Drivetrain', 'Electrical', 'Electronics', 'Engine', 'ERS', 'Excluded', 
              'Exhaust', 'Finished', 'Front wing', 'Fuel leak', 'Fuel pressure', 'Fuel pump', 'Fuel system', 'Gearbox', 'Hydraulics', 
              'Illness', 'Mechanical', 'Oil leak', 'Oil pressure', 'Out of fuel', 'Overheating', 'Pneumatics', 'Power loss', 
              'Power Unit', 'Puncture', 'Radiator', 'Rear wing', 'Retired', 'Seat', 'Spark plugs', 'Spun off', 'Steering', 'Suspension',
              'Technical', 'Throttle', 'Transmission', 'Turbo', 'Tyre', 'Undertray', 'Vibrations', 'Water leak', 'Water pressure', 
              'Water pump', 'Wheel', 'Wheel nut', 'Withdrew']

  - name: stg_constructors
    description: The constructors table.
    columns:
      - name: constructor_id
        description: Primary key to constructors table
        tests:
          - unique
          - not_null

  - name: stg_schedules
    columns:
      - name: datetime
        tests:
          - unique
          - not_null
      - name: circuit_id
        description: Foreign key to stg_circuits.circuitId
        tests:
          - not_null
          - relationships:
              to: ref('stg_circuits')
              field: circuit_id
      - name: season
        description: Foreign key to stg_seasons.season
        tests:
          - not_null
          - relationships:
              to: ref('stg_seasons')
              field: season

  - name: stg_seasons
    columns:
      - name: season
        tests:
          - unique
          - not_null

  - name: stg_drivers
    columns:
      - name: driver_id
        description: Primary key for drivers.
        tests:
          - unique
          - not_null

  - name: stg_circuits
    columns:
      - name: circuit_id
        tests:
          - unique
          - not_null
