#profiles.yml is NOT needed by Airflow to run dbt models. The connections for that are specified in the airflow .py file.
#This profile.yml was created to allow manual running of "dbt docs generate" in the container (webserver) which create a webui on https://localhost:8001
#to view model relationships and docs.

jaffle_shop_db:
  target: prod
  outputs:
    prod:
      type: postgres
      host: postgres-dev.cluster-c2k5rcppbf2p.us-east-1.rds.amazonaws.com
      user: postgres
      password: <password>
      port: 5432
      dbname: postgres
      schema: public
      threads: 1

    dev:
      type: postgres
      host: postgres-dev.cluster-c2k5rcppbf2p.us-east-1.rds.amazonaws.com
      user: postgres
      password: <password>
      port: 5432
      dbname: postgres
      schema: dev
      threads: 1