'''profiles.yml is NOT needed by Airflow to run dbt models. The connections for that are specified in the airflow .py file.
This profile.yml was created to allow manual running of "dbt docs generate" in the container (webserver) which create a webui on https://localhost:8001
to view model relationships and docs.
'''
jaffle_shop_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: <db_host>
      user: <user>
      password: <password>
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: public
      threads: 1
      # [keepalives_idle]: 0 # default 0, indicating the system default. See below
      # connect_timeout: 10 # default 10 seconds
      # [retries](#retries): 1  # default 1 retry on error/timeout when opening connections
      # # [search_path](#search_path): [optional, override the default postgres search_path]
      # # [role](#role): [optional, set the role dbt assumes when executing queries]
